# adapted from https://github.com/rblaine95/dockerhub-mirror/blob/master/.github/workflows/mirror.yml
name: Mirror Gitpod images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: gitpod/workspace-full
            repo: docker.io
          - image: gitpod/openvscode-server
            repo: docker.io
          - image: gitpod/workspace-java-17
            repo: docker.io
          - image: gitpod/workspace-mongodb
            repo: docker.io
          - image: gitpod/workspace-mongodb
            repo: docker.io

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: actions/setup-go@v3
      - uses: imjasonh/setup-crane@v0.3
      - name: Mirror
        run: |
          for tag in $(crane ls ${{ matrix.repo }}/${{ matrix.image }}); do
            crane copy \
              ${{ matrix.repo }}/${{ matrix.image }}:$tag \
              ghcr.io/${{ github.repository_owner }}/${{ matrix.image//[\/]/[-] }}:$tag
          done
